name: Docker Image CI

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
     
  login:
    runs-on: ubuntu-latest
    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: bfhmea4
          password: ${{ secrets.GITHUB_TOKEN }}
 
      - name: Build and Push the Docker image
        uses: docker/build-push-action@v2
        with:
        
          tags: bfhmea4/mea4_03_rides:latest
          push: true
      
    
